stages:
  get_data:
    cmd: python x1_get_data.py
    deps:
    - x1_get_data.py
    outs:
    - test.py
    - train.py
  process_data:
    cmd: python x2_process_data.py
    deps:
    - x2_process_data.py
    - test.py
    - train.py
    outs:
    - data_processed.csv
  train_data:
    cmd: python x3_train.py
    deps:
    - x3_train.py
    - data_processed.csv
    outs:
    - ROC.png
    metrics:
     - metrics.json:
          cache: false 
    
